language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t danielwong0323/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielwong0323/react-test npm test

after_success:
  - docker build -t danielwong0323/multi-client ./client
  - docker build -t danielwong0323/multi-nginx ./nginx
  - docker build -t danielwong0323/multi-server ./server
  - docker build -t danielwong0323/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push danielwong0323/multi-client
  - docker push danielwong0323/multi-nginx
  - docker push danielwong0323/multi-server
  - docker push danielwong0323/multi-worker
